### ISSUE TITLE
problem with custom widget class

### ISSUE THREAD

**Issue by waleed-sarwar** [jaumard/ngx-dashboard#25] opened 2017-07-20 12:55 UTC
hi once again,

i add class to custom widget using re.addClass the class added but it cant find those classes although i added.. is it something missing ???

![image](https://user-images.githubusercontent.com/30215747/28418280-94050c62-6d74-11e7-96b9-12e33556930e.png)

`addWidget() {
     const ref: MyWidgetComponent = this.dashboard.addItem(MyWidgetComponent);
     ref.setSize([this.static_width, this.static_height]);
     ref.addClass('notes-box')
     ref.widgetId = '123123';
     ref.type = 'notes';
     ref.title = 'notes';
     ref.content = 'notes';
     ref.close = this.close;
     ref.dashboard = this.dashboard;
  }`

**Comment by waleed-sarwar** [comment] 2017-07-20 13:49
it works when i add class in main index.html file

**Comment by jaumard** [comment] 2017-07-21 08:20
I think that if you call it directly after adding the widget on dashboard it will not work because widget is not ready yet you need to listen for AfterViewInit event of your widget component and do it here (or after this event when the widget is ready)

**Comment by jaumard** [comment] 2017-07-26 14:57
@waleed-sarwar is it ok ?

**Comment by jaumard** [comment] 2017-07-28 13:26
Closing this one as the problem is not part of this library

**Closed as completed by jaumard** 2017-07-28 13:26 UTC

**Comment by waleed-sarwar** [comment] 2017-07-28 13:32
yes its ok thanks
